package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



/**
 * LtIdentifyingNumber generated by hbm2java
 */
@Entity
@Table(name = "LT_IDENTIFYING_NUMBER")
@SequenceGenerator(name = "LT_IDENTIFYING_NUMBER_SEQ", sequenceName = "LT_IDENTIFYING_NUMBER_SEQ", allocationSize = 1, initialValue = 1)
public class LtIdentifyingNumber extends BaseEntity {

	private Long id;
	private EventTypeCode eventTypeCode;
	private StatusCode statusCodeByTecsCaseStatusCodeId;
	private StatusCode statusCodeByTecsSubjectRcStatusCodeId;
	private LtUser ltUserByModifiedBy;
	private ApplicationLocationCode applicationLocationCode;
	private VisaClassCode visaClassCode;
	private NumberTypeCode numberTypeCode;
	private StateProvinceCode stateProvinceCode;
	private LtUser ltUserByCreateBy;
	private LicenseTypeCode licenseTypeCode;
	private CountryCode countryCode;
	private String identifyingNumber;
	private String issueLocation;
	private String identifyingNumberComment;
	private String otherType;
	private Date tecsSubjectRcCreateDate;
	private Date tecsSubjectRcUpdateDate;
	private Date tecsIlogIncidentDate;
	private Date naturalizationDate;
	private Date issueDate;
	private Date expirationDate;
	private Date eventDate;
	private Date createDate;
	private Date modifiedDate;
	private Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers = new HashSet<LtLeadIdentifyingNumber>(
			0);
	private Set<LtIdentifyingNumberSource> ltIdentifyingNumberSources = new HashSet<LtIdentifyingNumberSource>(
			0);

	public LtIdentifyingNumber() {
	}

	public LtIdentifyingNumber(Long id, LtUser ltUserByModifiedBy,
			NumberTypeCode numberTypeCode, LtUser ltUserByCreateBy,
			String identifyingNumber, Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.numberTypeCode = numberTypeCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.identifyingNumber = identifyingNumber;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	public LtIdentifyingNumber(Long id, EventTypeCode eventTypeCode,
			StatusCode statusCodeByTecsCaseStatusCodeId,
			StatusCode statusCodeByTecsSubjectRcStatusCodeId,
			LtUser ltUserByModifiedBy,
			ApplicationLocationCode applicationLocationCode,
			VisaClassCode visaClassCode, NumberTypeCode numberTypeCode,
			StateProvinceCode stateProvinceCode, LtUser ltUserByCreateBy,
			LicenseTypeCode licenseTypeCode, CountryCode countryCode,
			String identifyingNumber, String issueLocation,
			String identifyingNumberComment, String otherType,
			Date tecsSubjectRcCreateDate, Date tecsSubjectRcUpdateDate,
			Date tecsIlogIncidentDate, Date naturalizationDate, Date issueDate,
			Date expirationDate, Date eventDate, Date createDate,
			Date modifiedDate,
			Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers,
			Set<LtIdentifyingNumberSource> ltIdentifyingNumberSources) {
		this.id = id;
		this.eventTypeCode = eventTypeCode;
		this.statusCodeByTecsCaseStatusCodeId = statusCodeByTecsCaseStatusCodeId;
		this.statusCodeByTecsSubjectRcStatusCodeId = statusCodeByTecsSubjectRcStatusCodeId;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.applicationLocationCode = applicationLocationCode;
		this.visaClassCode = visaClassCode;
		this.numberTypeCode = numberTypeCode;
		this.stateProvinceCode = stateProvinceCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.licenseTypeCode = licenseTypeCode;
		this.countryCode = countryCode;
		this.identifyingNumber = identifyingNumber;
		this.issueLocation = issueLocation;
		this.identifyingNumberComment = identifyingNumberComment;
		this.otherType = otherType;
		this.tecsSubjectRcCreateDate = tecsSubjectRcCreateDate;
		this.tecsSubjectRcUpdateDate = tecsSubjectRcUpdateDate;
		this.tecsIlogIncidentDate = tecsIlogIncidentDate;
		this.naturalizationDate = naturalizationDate;
		this.issueDate = issueDate;
		this.expirationDate = expirationDate;
		this.eventDate = eventDate;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.ltLeadIdentifyingNumbers = ltLeadIdentifyingNumbers;
		this.ltIdentifyingNumberSources = ltIdentifyingNumberSources;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_IDENTIFYING_NUMBER_SEQ")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_TYPE_CODE_ID")
	public EventTypeCode getEventTypeCode() {
		return this.eventTypeCode;
	}

	public void setEventTypeCode(EventTypeCode eventTypeCode) {
		this.eventTypeCode = eventTypeCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TECS_CASE_STATUS_CODE_ID")
	public StatusCode getStatusCodeByTecsCaseStatusCodeId() {
		return this.statusCodeByTecsCaseStatusCodeId;
	}

	public void setStatusCodeByTecsCaseStatusCodeId(
			StatusCode statusCodeByTecsCaseStatusCodeId) {
		this.statusCodeByTecsCaseStatusCodeId = statusCodeByTecsCaseStatusCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TECS_SUBJECT_RC_STATUS_CODE_ID")
	public StatusCode getStatusCodeByTecsSubjectRcStatusCodeId() {
		return this.statusCodeByTecsSubjectRcStatusCodeId;
	}

	public void setStatusCodeByTecsSubjectRcStatusCodeId(
			StatusCode statusCodeByTecsSubjectRcStatusCodeId) {
		this.statusCodeByTecsSubjectRcStatusCodeId = statusCodeByTecsSubjectRcStatusCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLICATION_LOCATION_CODE_ID")
	public ApplicationLocationCode getApplicationLocationCode() {
		return this.applicationLocationCode;
	}

	public void setApplicationLocationCode(
			ApplicationLocationCode applicationLocationCode) {
		this.applicationLocationCode = applicationLocationCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VISA_CLASS_CODE_ID")
	public VisaClassCode getVisaClassCode() {
		return this.visaClassCode;
	}

	public void setVisaClassCode(VisaClassCode visaClassCode) {
		this.visaClassCode = visaClassCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMBER_TYPE_CODE_ID", nullable = false)
	public NumberTypeCode getNumberTypeCode() {
		return this.numberTypeCode;
	}

	public void setNumberTypeCode(NumberTypeCode numberTypeCode) {
		this.numberTypeCode = numberTypeCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_PROVINCE_CODE_ID")
	public StateProvinceCode getStateProvinceCode() {
		return this.stateProvinceCode;
	}

	public void setStateProvinceCode(StateProvinceCode stateProvinceCode) {
		this.stateProvinceCode = stateProvinceCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LICENSE_TYPE_CODE_ID")
	public LicenseTypeCode getLicenseTypeCode() {
		return this.licenseTypeCode;
	}

	public void setLicenseTypeCode(LicenseTypeCode licenseTypeCode) {
		this.licenseTypeCode = licenseTypeCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE_ID")
	public CountryCode getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(CountryCode countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "IDENTIFYING_NUMBER", nullable = false, length = 100)
	public String getIdentifyingNumber() {
		return this.identifyingNumber;
	}

	public void setIdentifyingNumber(String identifyingNumber) {
		this.identifyingNumber = identifyingNumber;
	}

	@Column(name = "ISSUE_LOCATION", length = 100)
	public String getIssueLocation() {
		return this.issueLocation;
	}

	public void setIssueLocation(String issueLocation) {
		this.issueLocation = issueLocation;
	}

	@Column(name = "IDENTIFYING_NUMBER_COMMENT", length = 4000)
	public String getIdentifyingNumberComment() {
		return this.identifyingNumberComment;
	}

	public void setIdentifyingNumberComment(String identifyingNumberComment) {
		this.identifyingNumberComment = identifyingNumberComment;
	}

	@Column(name = "OTHER_TYPE", length = 100)
	public String getOtherType() {
		return this.otherType;
	}

	public void setOtherType(String otherType) {
		this.otherType = otherType;
	}

	
	@Column(name = "TECS_SUBJECT_RC_CREATE_DATE", length = 7)
	public Date getTecsSubjectRcCreateDate() {
		return this.tecsSubjectRcCreateDate;
	}

	public void setTecsSubjectRcCreateDate(Date tecsSubjectRcCreateDate) {
		this.tecsSubjectRcCreateDate = tecsSubjectRcCreateDate;
	}

	
	@Column(name = "TECS_SUBJECT_RC_UPDATE_DATE", length = 7)
	public Date getTecsSubjectRcUpdateDate() {
		return this.tecsSubjectRcUpdateDate;
	}

	public void setTecsSubjectRcUpdateDate(Date tecsSubjectRcUpdateDate) {
		this.tecsSubjectRcUpdateDate = tecsSubjectRcUpdateDate;
	}

	
	@Column(name = "TECS_ILOG_INCIDENT_DATE", length = 7)
	public Date getTecsIlogIncidentDate() {
		return this.tecsIlogIncidentDate;
	}

	public void setTecsIlogIncidentDate(Date tecsIlogIncidentDate) {
		this.tecsIlogIncidentDate = tecsIlogIncidentDate;
	}

	
	@Column(name = "NATURALIZATION_DATE", length = 7)
	public Date getNaturalizationDate() {
		return this.naturalizationDate;
	}

	public void setNaturalizationDate(Date naturalizationDate) {
		this.naturalizationDate = naturalizationDate;
	}

	
	@Column(name = "ISSUE_DATE", length = 7)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	
	@Column(name = "EXPIRATION_DATE", length = 7)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	
	@Column(name = "EVENT_DATE", length = 7)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltIdentifyingNumber")
	public Set<LtLeadIdentifyingNumber> getLtLeadIdentifyingNumbers() {
		return this.ltLeadIdentifyingNumbers;
	}

	public void setLtLeadIdentifyingNumbers(
			Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers) {
		this.ltLeadIdentifyingNumbers = ltLeadIdentifyingNumbers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltIdentifyingNumber", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	public Set<LtIdentifyingNumberSource> getLtIdentifyingNumberSources() {
		return this.ltIdentifyingNumberSources;
	}

	public void setLtIdentifyingNumberSources(
			Set<LtIdentifyingNumberSource> ltIdentifyingNumberSources) {
		this.ltIdentifyingNumberSources = ltIdentifyingNumberSources;
	}

}
