package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;



/**
 * LtLeadComment generated by hbm2java
 */
@XmlRootElement
//@XmlType(propOrder={"id","leadComment","createDate","modifiedDate"})
@Entity
@Table(name = "LT_LEAD_COMMENT")
@SequenceGenerator(name = "LT_LEAD_COMMENT_SEQ", sequenceName = "LT_LEAD_COMMENT_SEQ", allocationSize = 1, initialValue = 1)
public class LtLeadComment extends BaseEntity {

    private Long id;
	private LtUser ltUserByModifiedBy;
	private LtLead ltLead;
	private LtUser ltUserByCreateBy;
	private String leadComment;
	private Date createDate;
	private Date modifiedDate;

	public LtLeadComment() {
	}

	public LtLeadComment(//LtLeadCommentId id,
			Long id,
			LtUser ltUserByModifiedBy,
			LtLead ltLead, LtUser ltUserByCreateBy, String leadComment,
			Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltLead = ltLead;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.leadComment = leadComment;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_LEAD_COMMENT_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlElement
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_LEAD_ID", nullable = false)
	public LtLead getLtLead() {
		return this.ltLead;
	}

	@XmlTransient
	public void setLtLead(LtLead ltLead) {
		this.ltLead = ltLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlElement
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "LEAD_COMMENT", nullable = false, length = 4000)
	public String getLeadComment() {
		return this.leadComment;
	}

	@XmlElement
	public void setLeadComment(String leadComment) {
		this.leadComment = leadComment;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	
	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
