package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;



/**
 * LtLeadSpecialProject generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_LEAD_SPECIAL_PROJECT")
public class LtLeadSpecialProject extends BaseEntity {

	private CompositeId id;
	private SpecialProjectCode specialProjectCode;
	private LtUser ltUserByModifiedBy;
	private LtLead ltLead;
	private LtUser ltUserByCreateBy;
	private String leadSpecialProjectComment;
	private Date createDate;
	private Date modifiedDate;

	public LtLeadSpecialProject() {
	}

	public LtLeadSpecialProject(CompositeId id,
			SpecialProjectCode specialProjectCode, LtUser ltUserByModifiedBy,
			LtLead ltLead, LtUser ltUserByCreateBy,
			String leadSpecialProjectComment, Date createDate, Date modifiedDate) {
		this.id = id;
		this.specialProjectCode = specialProjectCode;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltLead = ltLead;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.leadSpecialProjectComment = leadSpecialProjectComment;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "LT_LEAD_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "compId", column = @Column(name = "SPECIAL_PROJECT_CODE_ID", nullable = false, precision = 22, scale = 0)) })
	public CompositeId getId() {
		return this.id;
	}

	@XmlElement
	public void setId(CompositeId id) {
		this.id = id;
	}

	@MapsId(value="compId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPECIAL_PROJECT_CODE_ID", nullable = false, insertable = false, updatable = false)
	public SpecialProjectCode getSpecialProjectCode() {
		return this.specialProjectCode;
	}

	@XmlElement
	public void setSpecialProjectCode(SpecialProjectCode specialProjectCode) {
		this.specialProjectCode = specialProjectCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@MapsId(value="id")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_LEAD_ID", nullable = false, insertable = false, updatable = false)
	public LtLead getLtLead() {
		return this.ltLead;
	}

	@XmlTransient
	public void setLtLead(LtLead ltLead) {
		this.ltLead = ltLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "LEAD_SPECIAL_PROJECT_COMMENT", nullable = false, length = 4000)
	public String getLeadSpecialProjectComment() {
		return this.leadSpecialProjectComment;
	}

	@XmlElement
	public void setLeadSpecialProjectComment(String leadSpecialProjectComment) {
		this.leadSpecialProjectComment = leadSpecialProjectComment;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
