package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;



/**
 * LtLeadHistory generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_LEAD_HISTORY")
@SequenceGenerator(name = "LT_LEAD_HISTORY_SEQ", sequenceName = "LT_LEAD_HISTORY_SEQ", allocationSize = 1, initialValue = 1)
public class LtLeadHistory extends BaseEntity {

	private Long id;
	private LtUser ltUserByModifiedBy;
	private LtLead ltLead;
	private ActionCode actionCode;
	private LtUser ltUserByCreateBy;
	private LtUser takenBy;
	private Date takenDate;
	private String detail;
	private Date createDate;
	private Date modifiedDate;

	public LtLeadHistory() {
	}

	public LtLeadHistory(Long id, LtUser ltUserByModifiedBy, LtLead ltLead,
			ActionCode actionCode, LtUser ltUserByCreateBy, LtUser takenBy,
			Date takenDate, String detail, Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltLead = ltLead;
		this.actionCode = actionCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.takenBy = takenBy;
		this.takenDate = takenDate;
		this.detail = detail;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_LEAD_HISTORY_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_LEAD_ID", nullable = false)
	public LtLead getLtLead() {
		return this.ltLead;
	}

	@XmlTransient
	public void setLtLead(LtLead ltLead) {
		this.ltLead = ltLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTION_CODE_ID", nullable = false)
	public ActionCode getActionCode() {
		return this.actionCode;
	}

	@XmlElement
	public void setActionCode(ActionCode actionCode) {
		this.actionCode = actionCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAKEN_BY", nullable = false)
	public LtUser getTakenBy() {
		return this.takenBy;
	}

	@XmlTransient
	public void setTakenBy(LtUser takenBy) {
		this.takenBy = takenBy;
	}

	
	@Column(name = "TAKEN_DATE", nullable = false)
	public Date getTakenDate() {
		return this.takenDate;
	}

	@XmlElement
	public void setTakenDate(Date takenDate) {
		this.takenDate = takenDate;
	}

	@Column(name = "DETAIL", nullable = false, length = 100)
	public String getDetail() {
		return this.detail;
	}

	@XmlElement
	public void setDetail(String detail) {
		this.detail = detail;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
