package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;



/**
 * LtLeadSource generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_LEAD_SOURCE")
@SequenceGenerator(name = "LT_LEAD_SOURCE_SEQ", sequenceName = "LT_LEAD_SOURCE_SEQ", allocationSize = 1, initialValue = 1)
public class LtLeadSource extends BaseEntity {

	private Long id;
	private LtUser ltUserByModifiedBy;
	private LtLead ltLead;
	private ContactTypeCode contactTypeCode;
	private LtUser ltUserByCreateBy;
	private String name;
	private String title;
	private String contact;
	private Date createDate;
	private Date modifiedDate;
	private Set<LtLead> ltLeads = new HashSet<LtLead>(0);

	public LtLeadSource() {
	}

	public LtLeadSource(Long id, LtUser ltUserByModifiedBy, LtLead ltLead,
			ContactTypeCode contactTypeCode, LtUser ltUserByCreateBy,
			String name, String title, String contact, Date createDate,
			Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltLead = ltLead;
		this.contactTypeCode = contactTypeCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.name = name;
		this.title = title;
		this.contact = contact;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	public LtLeadSource(Long id, LtUser ltUserByModifiedBy, LtLead ltLead,
			ContactTypeCode contactTypeCode, LtUser ltUserByCreateBy,
			String name, String title, String contact, Date createDate,
			Date modifiedDate, Set<LtLead> ltLeads) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltLead = ltLead;
		this.contactTypeCode = contactTypeCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.name = name;
		this.title = title;
		this.contact = contact;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.ltLeads = ltLeads;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_LEAD_SOURCE_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_LEAD_ID")
	public LtLead getLtLead() {
		return this.ltLead;
	}

	@XmlTransient
	public void setLtLead(LtLead ltLead) {
		this.ltLead = ltLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTACT_TYPE_CODE_ID", nullable = false)
	public ContactTypeCode getContactTypeCode() {
		return this.contactTypeCode;
	}

	@XmlElement
	public void setContactTypeCode(ContactTypeCode contactTypeCode) {
		this.contactTypeCode = contactTypeCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	@XmlElement
	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TITLE", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	@XmlElement
	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTACT", nullable = false, length = 100)
	public String getContact() {
		return this.contact;
	}

	@XmlElement
	public void setContact(String contact) {
		this.contact = contact;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

////	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLeadSource")
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLeadSource", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
//	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
//	public Set<LtLead> getLtLeads() {
//		return this.ltLeads;
//	}
//
//	public void setLtLeads(Set<LtLead> ltLeads) {
//		this.ltLeads = ltLeads;
//	}

}
