package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LtSubjectContactSourceId generated by hbm2java
 */
@Embeddable
public class LtLeadSourceId extends BaseEntity {

    private Long ltLeadId;
    private Long id;

    public LtLeadSourceId() {
    }

    public LtLeadSourceId(long ltLeadId, Long id) {
	this.ltLeadId = ltLeadId;
	this.id = id;
    }

    @Column(name = "LT_LEAD_ID", nullable = false, precision = 22, scale = 0)
    public long getLtLeadId() {
	return this.ltLeadId;
    }

    public void setLtLeadId(long ltLeadId) {
	this.ltLeadId = ltLeadId;
    }

    @Column(name = "ID", nullable = false, precision = 22, scale = 0)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof LtLeadSourceId))
	    return false;
	LtLeadSourceId castOther = (LtLeadSourceId) other;

	return (this.getLtLeadId() == castOther.getLtLeadId())
		&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + (int) this.getLtLeadId();
	result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
	return result;
    }

}
