package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Cascade;

/**
 * LtLead generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_LEAD")
@SequenceGenerator(name = "LT_LEAD_SEQ", sequenceName = "LT_LEAD_SEQ", allocationSize = 1, initialValue = 1)
public class LtLead extends BaseEntity {

	private Long id;
	private String ltid;

	private LtUser ltUserByModifiedBy;
	private MissionCode missionCode;
	private DisposCloseSystemCode disposCloseSystemCode;
	private LtSubject ltSubject;
	private LtUser ltUserByLtAssignToUserId;
	private LeadTypeCode leadTypeCode;
	private LeadGeneratedFromCode leadGeneratedFromCode;
	private LtUser ltUserByCreateBy;
	private StatusCode statusCode;
	private DisposCloseReasonCode disposCloseReasonCode;
	private Date createDate;
	private Date modifiedDate;
	private Date callUpDate;
	private Set<LtAssociatedLead> ltAssociatedLeadsForLtLeadId = new HashSet<LtAssociatedLead>(0);
	private Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers = new HashSet<LtLeadIdentifyingNumber>(0);
	private Set<LtLeadComment> ltLeadComments = new HashSet<LtLeadComment>(0);
	private Set<LtLeadSpecialProject> ltLeadSpecialProjects = new HashSet<LtLeadSpecialProject>(0);
	private Set<LtLeadHistory> ltLeadHistories = new HashSet<LtLeadHistory>(0);
	private Set<LtAssociatedLead> ltAssociatedLeadsForLtAssociatedLeadId = new HashSet<LtAssociatedLead>(0);
	private Set<LtLeadSource> ltLeadSources = new HashSet<LtLeadSource>(0);
	private Set<LtLeadSubject> ltLeadSubjects = new HashSet<LtLeadSubject>(0);

	public LtLead() {
	}

	public LtLead(Long id, LtUser ltUserByModifiedBy, LtSubject ltSubject, LeadTypeCode leadTypeCode, LeadGeneratedFromCode leadGeneratedFromCode, LtUser ltUserByCreateBy,
	        StatusCode statusCode, Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltSubject = ltSubject;
		this.leadTypeCode = leadTypeCode;
		this.leadGeneratedFromCode = leadGeneratedFromCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.statusCode = statusCode;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	public LtLead(Long id, LtUser ltUserByModifiedBy, MissionCode missionCode, DisposCloseSystemCode disposCloseSystemCode, LtSubject ltSubject, LtUser ltUserByLtAssignToUserId,
	        LeadTypeCode leadTypeCode, LeadGeneratedFromCode leadGeneratedFromCode, LtUser ltUserByCreateBy, StatusCode statusCode, DisposCloseReasonCode disposCloseReasonCode,
	        Date createDate, Date modifiedDate, Set<LtAssociatedLead> ltAssociatedLeadsForLtLeadId, Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers,
	        Set<LtLeadComment> ltLeadComments, Set<LtLeadSpecialProject> ltLeadSpecialProjects, Set<LtLeadHistory> ltLeadHistories,
	        Set<LtAssociatedLead> ltAssociatedLeadsForLtAssociatedLeadId, Set<LtLeadSource> ltLeadSources, Set<LtLeadSubject> ltLeadSubjects) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.missionCode = missionCode;
		this.disposCloseSystemCode = disposCloseSystemCode;
		this.ltSubject = ltSubject;
		this.ltUserByLtAssignToUserId = ltUserByLtAssignToUserId;
		this.leadTypeCode = leadTypeCode;
		this.leadGeneratedFromCode = leadGeneratedFromCode;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.statusCode = statusCode;
		this.disposCloseReasonCode = disposCloseReasonCode;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.ltAssociatedLeadsForLtLeadId = ltAssociatedLeadsForLtLeadId;
		this.ltLeadIdentifyingNumbers = ltLeadIdentifyingNumbers;
		this.ltLeadComments = ltLeadComments;
		this.ltLeadSpecialProjects = ltLeadSpecialProjects;
		this.ltLeadHistories = ltLeadHistories;
		this.ltAssociatedLeadsForLtAssociatedLeadId = ltAssociatedLeadsForLtAssociatedLeadId;
		this.ltLeadSources = ltLeadSources;
		this.ltLeadSubjects = ltLeadSubjects;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_LEAD_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LTID", nullable = false, length = 1000)
	public String getLtid() {
		return this.ltid;
	}

	@XmlElement
	public void setLtid(String ltid) {
		this.ltid = ltid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_CODE_ID")
	public MissionCode getMissionCode() {
		return this.missionCode;
	}

	@XmlElement
	public void setMissionCode(MissionCode missionCode) {
		this.missionCode = missionCode;
	}

	@JoinColumn(name = "DISPOS_CLOSE_SYSTEM_CODE_ID")
	@ManyToOne(fetch = FetchType.LAZY)
	public DisposCloseSystemCode getDisposCloseSystemCode() {
		return this.disposCloseSystemCode;
	}

	@XmlElement
	public void setDisposCloseSystemCode(DisposCloseSystemCode disposCloseSystemCode) {
		this.disposCloseSystemCode = disposCloseSystemCode;
	}

	@JoinColumn(name = "LT_SUBJECT_ID", nullable = true)
	@ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
	public LtSubject getLtSubject() {
		return this.ltSubject;
	}

	@XmlElement
	public void setLtSubject(LtSubject ltSubject) {
		this.ltSubject = ltSubject;
	}

	@JoinColumn(name = "LT_ASSIGN_TO_USER_ID")
	@ManyToOne(fetch = FetchType.LAZY)
	public LtUser getLtUserByLtAssignToUserId() {
		return this.ltUserByLtAssignToUserId;
	}

	@XmlTransient
	public void setLtUserByLtAssignToUserId(LtUser ltUserByLtAssignToUserId) {
		this.ltUserByLtAssignToUserId = ltUserByLtAssignToUserId;
	}

	@JoinColumn(name = "LEAD_TYPE_CODE_ID", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LeadTypeCode getLeadTypeCode() {
		return this.leadTypeCode;
	}

	@XmlElement
	public void setLeadTypeCode(LeadTypeCode leadTypeCode) {
		this.leadTypeCode = leadTypeCode;
	}

	@JoinColumn(name = "LEAD_GENERATED_FROM_CODE_ID", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LeadGeneratedFromCode getLeadGeneratedFromCode() {
		return this.leadGeneratedFromCode;
	}

	@XmlElement
	public void setLeadGeneratedFromCode(LeadGeneratedFromCode leadGeneratedFromCode) {
		this.leadGeneratedFromCode = leadGeneratedFromCode;
	}

	@JoinColumn(name = "CREATE_BY", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@JoinColumn(name = "LEAD_STATUS_CODE_ID", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	@XmlElement
	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@JoinColumn(name = "DISPOS_CLOSE_REASON_CODE_ID")
	@ManyToOne(fetch = FetchType.LAZY)
	public DisposCloseReasonCode getDisposCloseReasonCode() {
		return this.disposCloseReasonCode;
	}

	@XmlElement
	public void setDisposCloseReasonCode(DisposCloseReasonCode disposCloseReasonCode) {
		this.disposCloseReasonCode = disposCloseReasonCode;
	}

	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	
	@Column(name = "CALL_UP_DATE" , nullable = true)
	public Date getCallUpDate(){
		return this.callUpDate;
	}
	
	@XmlElement
	public void setCallUpDate(Date callUpdate){
		this.callUpDate = callUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLeadByLtLeadId", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtAssociatedLead> getLtAssociatedLeadsForLtLeadId() {
		return this.ltAssociatedLeadsForLtLeadId;
	}

	@XmlTransient
	public void setLtAssociatedLeadsForLtLeadId(Set<LtAssociatedLead> ltAssociatedLeadsForLtLeadId) {
		this.ltAssociatedLeadsForLtLeadId = ltAssociatedLeadsForLtLeadId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadIdentifyingNumber> getLtLeadIdentifyingNumbers() {
		return this.ltLeadIdentifyingNumbers;
	}

	@XmlTransient
	public void setLtLeadIdentifyingNumbers(Set<LtLeadIdentifyingNumber> ltLeadIdentifyingNumbers) {
		this.ltLeadIdentifyingNumbers = ltLeadIdentifyingNumbers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE }, orphanRemoval=true)
	@Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
	public Set<LtLeadComment> getLtLeadComments() {
		return this.ltLeadComments;
	}

	@XmlTransient
	public void setLtLeadComments(Set<LtLeadComment> ltLeadComments) {
		this.ltLeadComments = ltLeadComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadSpecialProject> getLtLeadSpecialProjects() {
		return this.ltLeadSpecialProjects;
	}

	@XmlElement
	public void setLtLeadSpecialProjects(Set<LtLeadSpecialProject> ltLeadSpecialProjects) {
		this.ltLeadSpecialProjects = ltLeadSpecialProjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadHistory> getLtLeadHistories() {
		return this.ltLeadHistories;
	}

	@XmlTransient
	public void setLtLeadHistories(Set<LtLeadHistory> ltLeadHistories) {
		this.ltLeadHistories = ltLeadHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLeadByLtAssociatedLeadId", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtAssociatedLead> getLtAssociatedLeadsForLtAssociatedLeadId() {
		return this.ltAssociatedLeadsForLtAssociatedLeadId;
	}

	@XmlTransient
	public void setLtAssociatedLeadsForLtAssociatedLeadId(Set<LtAssociatedLead> ltAssociatedLeadsForLtAssociatedLeadId) {
		this.ltAssociatedLeadsForLtAssociatedLeadId = ltAssociatedLeadsForLtAssociatedLeadId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadSource> getLtLeadSources() {
		return this.ltLeadSources;
	}

	@XmlElement
	public void setLtLeadSources(Set<LtLeadSource> ltLeadSources) {
		this.ltLeadSources = ltLeadSources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltLead", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadSubject> getLtLeadSubjects() {
		return this.ltLeadSubjects;
	}

	@XmlElement
	public void setLtLeadSubjects(Set<LtLeadSubject> ltLeadSubjects) {
		this.ltLeadSubjects = ltLeadSubjects;
	}
}
