package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * LtLead generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_LEAD_SUBJECT")
public class LtLeadSubject extends BaseEntity {

	private CompositeId id;

	private LtSubject ltSubject;

	private LtLead ltLead;

	private LtUser ltUserByCreateBy;

	private LtUser ltUserByModifiedBy;

	private Date createDate;

	private Date modifiedDate;

	public LtLeadSubject() {
	}

	public LtLeadSubject(CompositeId id, LtSubject ltSubject, LtLead ltLead,
			Long lsid, LtUser ltUserByCreateBy, LtUser ltUserByModifiedBy,
			Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltSubject = ltSubject;
		this.ltLead = ltLead;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "LT_LEAD_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "compId", column = @Column(name = "LT_SUBJECT_ID", nullable = false, precision = 22, scale = 0)) })
	public CompositeId getId() {
		return this.id;
	}

	@XmlElement
	public void setId(CompositeId id) {
		this.id = id;
	}

	@MapsId(value = "id")
	@JoinColumn(name = "LT_LEAD_ID", nullable = false, insertable = false, updatable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LtLead getLtLead() {
		return this.ltLead;
	}

	@XmlTransient
	public void setLtLead(LtLead ltLead) {
		this.ltLead = ltLead;
	}

	@MapsId(value = "compId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_SUBJECT_ID", nullable = false, insertable = false, updatable = false)
	public LtSubject getLtSubject() {
		return this.ltSubject;
	}

	@XmlElement
	public void setLtSubject(LtSubject ltSubject) {
		this.ltSubject = ltSubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@JoinColumn(name = "CREATE_BY", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
