package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * LtSubjectContactEmail generated by hbm2java
 */
@Entity
@Table(name = "LT_SUBJECT_CONTACT_EMAIL")
public class LtSubjectContactEmail extends BaseEntity {

	private Long id;
	private LtUser ltUserByModifiedBy;
	private LtSubjectContact ltSubjectContact;
	private LtUser ltUserByCreateBy;
	private String emailDescription;
	private Date validDate;
	private Date createDate;
	private Date modifiedDate;

	public LtSubjectContactEmail() {
	}

	public LtSubjectContactEmail(Long id, LtUser ltUserByModifiedBy,
			LtSubjectContact ltSubjectContact, LtUser ltUserByCreateBy,
			String emailDescription, Date validDate, Date createDate,
			Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltSubjectContact = ltSubjectContact;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.emailDescription = emailDescription;
		this.validDate = validDate;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_SUBJECT_CONTACT_ID", nullable = false)
	public LtSubjectContact getLtSubjectContact() {
		return this.ltSubjectContact;
	}

	public void setLtSubjectContact(LtSubjectContact ltSubjectContact) {
		this.ltSubjectContact = ltSubjectContact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "EMAIL_DESCRIPTION", nullable = false, length = 100)
	public String getEmailDescription() {
		return this.emailDescription;
	}

	public void setEmailDescription(String emailDescription) {
		this.emailDescription = emailDescription;
	}

	
	@Column(name = "VALID_DATE", nullable = false, length = 7)
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
