package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;



/**
 * LtUser generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_USER")
@SequenceGenerator(name = "LT_USER_SEQ", sequenceName = "LT_USER_SEQ", allocationSize = 1, initialValue = 1)
public class LtUser extends BaseEntity {

	private Long id;
	private LtUser ltUserByModifiedBy;
	private UserRoleCode userRoleCode;
	private LtUser ltUserByCreateBy;
	private String firstname;
	private String lastname;
	private String username;
	private String password;
	private Long enabled;
	private Date createDate;
	private Date modifiedDate;
	
	private Set<LtUserManagementAssociation> ltUserManagementAssociationsForSupervisorId = new HashSet<LtUserManagementAssociation>(
			0);
	private Set<LtLead> ltLeadsForLtAssignToUserId = new HashSet<LtLead>(0);
	private Set<MissionCodeUser> missionCodeUsersForLtUserId = new HashSet<MissionCodeUser>(
			0);
	private Set<LtUserManagementAssociation> ltUserManagementAssociationsForUserId = new HashSet<LtUserManagementAssociation>(
			0);

	public LtUser() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_USER_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ROLE_CODE_ID", nullable = false)
	@Fetch(FetchMode.JOIN)
	public UserRoleCode getUserRoleCode() {
		return this.userRoleCode;
	}

	@XmlElement
	public void setUserRoleCode(UserRoleCode userRoleCode) {
		this.userRoleCode = userRoleCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	@XmlElement
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", nullable = false, length = 100)
	public String getLastname() {
		return this.lastname;
	}

	@XmlElement
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "USERNAME", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	@XmlElement
	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	@XmlTransient
	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public Long getEnabled() {
		return this.enabled;
	}

	@XmlElement
	public void setEnabled(Long enabled) {
		this.enabled = enabled;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltUserBySupervisorId")
	public Set<LtUserManagementAssociation> getLtUserManagementAssociationsForSupervisorId() {
		return this.ltUserManagementAssociationsForSupervisorId;
	}

	@XmlTransient
	public void setLtUserManagementAssociationsForSupervisorId(
			Set<LtUserManagementAssociation> ltUserManagementAssociationsForSupervisorId) {
		this.ltUserManagementAssociationsForSupervisorId = ltUserManagementAssociationsForSupervisorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltUserByLtAssignToUserId")
	public Set<LtLead> getLtLeadsForLtAssignToUserId() {
		return this.ltLeadsForLtAssignToUserId;
	}

	@XmlTransient
	public void setLtLeadsForLtAssignToUserId(
			Set<LtLead> ltLeadsForLtAssignToUserId) {
		this.ltLeadsForLtAssignToUserId = ltLeadsForLtAssignToUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltUserByLtUserId")
	public Set<MissionCodeUser> getMissionCodeUsersForLtUserId() {
		return this.missionCodeUsersForLtUserId;
	}

	@XmlTransient
	public void setMissionCodeUsersForLtUserId(
			Set<MissionCodeUser> missionCodeUsersForLtUserId) {
		this.missionCodeUsersForLtUserId = missionCodeUsersForLtUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltUserByUserId")
	public Set<LtUserManagementAssociation> getLtUserManagementAssociationsForUserId() {
		return this.ltUserManagementAssociationsForUserId;
	}

	@XmlTransient
	public void setLtUserManagementAssociationsForUserId(
			Set<LtUserManagementAssociation> ltUserManagementAssociationsForUserId) {
		this.ltUserManagementAssociationsForUserId = ltUserManagementAssociationsForUserId;
	}

}
