package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import javax.persistence.UniqueConstraint;

/**
 * LicenseTypeCode generated by hbm2java
 */
@Entity
@Table(name = "LICENSE_TYPE_CODE", uniqueConstraints = @UniqueConstraint(columnNames = "ABBREVIATION"))
public class LicenseTypeCode extends BaseEntity {

	private Long id;
	private LtUser ltUserByModifiedBy;
	private LtUser ltUserByCreateBy;
	private String abbreviation;
	private String description;
	private Date createDate;
	private Date modifiedDate;
	private Set<LtIdentifyingNumber> ltIdentifyingNumbers = new HashSet<LtIdentifyingNumber>(
			0);

	public LicenseTypeCode() {
	}

	public LicenseTypeCode(Long id, LtUser ltUserByModifiedBy,
			LtUser ltUserByCreateBy, String abbreviation, String description,
			Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.abbreviation = abbreviation;
		this.description = description;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	public LicenseTypeCode(Long id, LtUser ltUserByModifiedBy,
			LtUser ltUserByCreateBy, String abbreviation, String description,
			Date createDate, Date modifiedDate,
			Set<LtIdentifyingNumber> ltIdentifyingNumbers) {
		this.id = id;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.abbreviation = abbreviation;
		this.description = description;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.ltIdentifyingNumbers = ltIdentifyingNumbers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "ABBREVIATION", unique = true, nullable = false, length = 100)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseTypeCode")
	public Set<LtIdentifyingNumber> getLtIdentifyingNumbers() {
		return this.ltIdentifyingNumbers;
	}

	public void setLtIdentifyingNumbers(
			Set<LtIdentifyingNumber> ltIdentifyingNumbers) {
		this.ltIdentifyingNumbers = ltIdentifyingNumbers;
	}

}
