package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AssociationOverrides;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LtLead generated by hbm2java
 */

@Entity
@Table(name = "LT_SUBJECT_TRAVEL_SOURCE")
public class LtSubjectTravelSource extends BaseEntity {

	private CompositeId id;
	private SourceCode sourceCode;
	private LtSubjectTravel ltSubjectTravel;

	private LtUser ltUserByCreateBy;

	private LtUser ltUserByModifiedBy;

	private Date createDate;

	private Date modifiedDate;

	public LtSubjectTravelSource() {
	}

	public LtSubjectTravelSource(CompositeId id, SourceCode sourceCode, LtSubjectTravel ltSubjectTravel, LtUser ltUserByCreateBy, LtUser ltUserByModifiedBy, Date createDate,
	        Date modifiedDate) {
		this.id = id;
		this.sourceCode = sourceCode;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltSubjectTravel = ltSubjectTravel;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "SOURCE_CODE_ID", nullable = false, precision = 22, scale = 0)),
	        @AttributeOverride(name = "compId", column = @Column(name = "LT_SUBJECT_TRAVEL_ID", nullable = false, precision = 22, scale = 0)) })
	public CompositeId getId() {
		return this.id;
	}

	public void setId(CompositeId id) {
		this.id = id;
	}

	@MapsId(value = "id")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCE_CODE_ID", nullable = false, insertable = false, updatable = false)
	public SourceCode getSourceCode() {
		return this.sourceCode;
	}

	public void setSourceCode(SourceCode sourceCode) {
		this.sourceCode = sourceCode;
	}

	@MapsId(value = "compId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LT_SUBJECT_TRAVEL_ID", nullable = false, insertable = false, updatable = false)
	public LtSubjectTravel getLtSubjectTravel() {
		return this.ltSubjectTravel;
	}

	public void setLtSubjectTravel(LtSubjectTravel ltSubjectTravel) {
		this.ltSubjectTravel = ltSubjectTravel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@JoinColumn(name = "CREATE_BY", nullable = false)
	@ManyToOne(fetch = FetchType.LAZY)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
