package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Cascade;

/**
 * LtSubject generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "LT_SUBJECT")
@SequenceGenerator(name = "LT_SUBJECT_SEQ", sequenceName = "LT_SUBJECT_SEQ", allocationSize = 1, initialValue = 1)
public class LtSubject extends BaseEntity {

	private Long id;

	private String lsid;

	private CountryCode countryCode;

	private LtUser ltUserByModifiedBy;

	private GenderCode genderCode;

	private LtUser ltUserByCreateBy;

	private PortEntryCode portEntryCode;

	private ClassAdmissionCode classAdmissionCode;

	private String lastname;

	private String firstname;

	private Date birthDate;

	private Date entryDate;

	private Date admitUntilDate;
	private Date adjustedAdmitUntilDate;

	private Character durationStatus;

	private Date departureDate;

	private Date createDate;

	private Date modifiedDate;

	private Set<LtSubjectPhoto> ltSubjectPhotos = new HashSet<LtSubjectPhoto>(0);
	private Set<LtSubjectContact> ltSubjectContacts = new HashSet<LtSubjectContact>(0);
	private Set<LtSubjectCitizenshipCountry> ltSubjectCitizenshipCountries = new HashSet<LtSubjectCitizenshipCountry>(0);
	private Set<LtLead> ltLeads = new HashSet<LtLead>(0);
	private Set<LtLeadSubject> ltLeadSubjects = new HashSet<LtLeadSubject>(0);
	private Set<LtAssociatedSubject> ltAssociatedSubjects = new HashSet<LtAssociatedSubject>(0);

	@Id
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "LT_SUBJECT_SEQ")
	public Long getId() {
		return this.id;
	}

	@XmlElement
	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LSID", nullable = false, length = 1000)
	public String getLsid() {
		return this.lsid;
	}

	@XmlElement
	public void setLsid(String lsid) {
		this.lsid = lsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE_BIRTH_ID")
	public CountryCode getCountryCode() {
		return this.countryCode;
	}

	@XmlElement
	public void setCountryCode(CountryCode countryCode) {
		this.countryCode = countryCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	@XmlTransient
	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENDER_CODE_ID")
	public GenderCode getGenderCode() {
		return this.genderCode;
	}

	@XmlElement
	public void setGenderCode(GenderCode genderCode) {
		this.genderCode = genderCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	@XmlTransient
	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PORT_ENTRY_CODE_ID")
	public PortEntryCode getPortEntryCode() {
		return this.portEntryCode;
	}

	@XmlElement
	public void setPortEntryCode(PortEntryCode portEntryCode) {
		this.portEntryCode = portEntryCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASS_ADMISSION_CODE_ID")
	public ClassAdmissionCode getClassAdmissionCode() {
		return this.classAdmissionCode;
	}

	@XmlElement
	public void setClassAdmissionCode(ClassAdmissionCode classAdmissionCode) {
		this.classAdmissionCode = classAdmissionCode;
	}

	@Column(name = "LASTNAME", nullable = false, length = 100)
	public String getLastname() {
		return this.lastname;
	}

	@XmlElement
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	@XmlElement
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "BIRTH_DATE", length = 7)
	public Date getBirthDate() {
		return this.birthDate;
	}

	@XmlElement
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "ENTRY_DATE", length = 7)
	public Date getEntryDate() {
		return this.entryDate;
	}

	@XmlElement
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "ADMIT_UNTIL_DATE", length = 7)
	public Date getAdmitUntilDate() {
		return this.admitUntilDate;
	}

	@XmlElement
	public void setAdmitUntilDate(Date admitUntilDate) {
		this.admitUntilDate = admitUntilDate;
	}

	@Column(name = "ADJUSTED_ADMIT_UNTIL_DATE", length = 7)
	public Date getAdjustedAdmitUntilDate() {
		return this.adjustedAdmitUntilDate;
	}

	@XmlElement
	public void setAdjustedAdmitUntilDate(Date adjustedAdmitUntilDate) {
		this.adjustedAdmitUntilDate = adjustedAdmitUntilDate;
	}

	@Column(name = "DURATION_STATUS", length = 1)
	public Character getDurationStatus() {
		return this.durationStatus;
	}

	@XmlElement
	public void setDurationStatus(Character durationStatus) {
		this.durationStatus = durationStatus;
	}

	@Column(name = "DEPARTURE_DATE", length = 7)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	@XmlElement
	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	@XmlElement
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	@XmlElement
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtSubjectPhoto> getLtSubjectPhotos() {
		return this.ltSubjectPhotos;
	}

	@XmlElement
	public void setLtSubjectPhotos(Set<LtSubjectPhoto> ltSubjectPhotos) {
		this.ltSubjectPhotos = ltSubjectPhotos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtSubjectContact> getLtSubjectContacts() {
		return this.ltSubjectContacts;
	}

	@XmlElement
	public void setLtSubjectContacts(Set<LtSubjectContact> ltSubjectContacts) {
		this.ltSubjectContacts = ltSubjectContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE }, orphanRemoval = true)
	@Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
	public Set<LtSubjectCitizenshipCountry> getLtSubjectCitizenshipCountries() {
		return this.ltSubjectCitizenshipCountries;
	}

	@XmlElement
	public void setLtSubjectCitizenshipCountries(Set<LtSubjectCitizenshipCountry> ltSubjectCitizenshipCountries) {
		this.ltSubjectCitizenshipCountries = ltSubjectCitizenshipCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
	public Set<LtLead> getLtLeads() {
		return this.ltLeads;
	}

	@XmlTransient
	public void setLtLeads(Set<LtLead> ltLeads) {
		this.ltLeads = ltLeads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Cascade(org.hibernate.annotations.CascadeType.REPLICATE)
	public Set<LtLeadSubject> getLtLeadSubjects() {
		return this.ltLeadSubjects;
	}

	@XmlTransient
	public void setLtLeadSubjects(Set<LtLeadSubject> ltLeadSubjects) {
		this.ltLeadSubjects = ltLeadSubjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ltSubject", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	public Set<LtAssociatedSubject> getLtAssociatedSubjects() {
		return this.ltAssociatedSubjects;
	}

	public void setLtAssociatedSubjects(Set<LtAssociatedSubject> ltAssociatedSubjects) {
		this.ltAssociatedSubjects = ltAssociatedSubjects;
	}
}
