package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;



/**
 * LtUserManagementAssociation generated by hbm2java
 */
@Entity
@Table(name = "LT_USER_MANAGEMENT_ASSOCIATION")
public class LtUserManagementAssociation extends BaseEntity {

	private CompositeId id;
	private LtUser ltUserByUserId;
	private LtUser ltUserBySupervisorId;
	private LtUser ltUserByModifiedBy;
	private LtUser ltUserByCreateBy;
	private Date createDate;
	private Date modifiedDate;

	public LtUserManagementAssociation() {
	}

	public LtUserManagementAssociation(CompositeId id,
			LtUser ltUserByUserId, LtUser ltUserBySupervisorId,
			LtUser ltUserByModifiedBy, LtUser ltUserByCreateBy,
			Date createDate, Date modifiedDate) {
		this.id = id;
		this.ltUserByUserId = ltUserByUserId;
		this.ltUserBySupervisorId = ltUserBySupervisorId;
		this.ltUserByModifiedBy = ltUserByModifiedBy;
		this.ltUserByCreateBy = ltUserByCreateBy;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "SUPERVISOR_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "compId", column = @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)) })
	public CompositeId getId() {
		return this.id;
	}

	public void setId(CompositeId id) {
		this.id = id;
	}

	@MapsId(value="compId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public LtUser getLtUserByUserId() {
		return this.ltUserByUserId;
	}

	public void setLtUserByUserId(LtUser ltUserByUserId) {
		this.ltUserByUserId = ltUserByUserId;
	}

	@MapsId(value="id")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPERVISOR_ID", nullable = false, insertable = false, updatable = false)
	public LtUser getLtUserBySupervisorId() {
		return this.ltUserBySupervisorId;
	}

	public void setLtUserBySupervisorId(LtUser ltUserBySupervisorId) {
		this.ltUserBySupervisorId = ltUserBySupervisorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getLtUserByModifiedBy() {
		return this.ltUserByModifiedBy;
	}

	public void setLtUserByModifiedBy(LtUser ltUserByModifiedBy) {
		this.ltUserByModifiedBy = ltUserByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getLtUserByCreateBy() {
		return this.ltUserByCreateBy;
	}

	public void setLtUserByCreateBy(LtUser ltUserByCreateBy) {
		this.ltUserByCreateBy = ltUserByCreateBy;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
