package co.adun.mvnejb3jpa.persistence.entity;

// Generated May 5, 2013 9:04:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlTransient;

/**
 * UserRoleCode generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_CODE", uniqueConstraints = @UniqueConstraint(columnNames = "ABBREVIATION"))
public class UserRoleCode extends BaseEntity {

	private Long id;
	private String abbreviation;
	private String description;
	private Date createDate;
	private LtUser createBy;
	private Date modifiedDate;
	private LtUser modifiedBy;

	public UserRoleCode() {
	}

	public UserRoleCode(Long id, String abbreviation, String description,
			Date createDate, LtUser createBy, Date modifiedDate,
			LtUser modifiedBy) {
		this.id = id;
		this.abbreviation = abbreviation;
		this.description = description;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	public UserRoleCode(Long id, String abbreviation, String description,
			Date createDate, LtUser createBy, Date modifiedDate,
			LtUser modifiedBy, Set<LtUser> ltUsers) {
		this.id = id;
		this.abbreviation = abbreviation;
		this.description = description;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ABBREVIATION", unique = true, nullable = false, length = 100)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	@Column(name = "CREATE_DATE", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY", nullable = false)
	public LtUser getCreateBy() {
		return this.createBy;
	}

	@XmlTransient
	public void setCreateBy(LtUser createBy) {
		this.createBy = createBy;
	}

	@Column(name = "MODIFIED_DATE", nullable = false)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public LtUser getModifiedBy() {
		return this.modifiedBy;
	}

	@XmlTransient
	public void setModifiedBy(LtUser modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
